runtime: python39

instance_class: F4

env_variables:
  DJANGO_SETTINGS_MODULE: 'config.settings'
  PYTHONUNBUFFERED: 'True'
  DEBUG: 'False'
  ALLOWED_HOSTS: 'your-app-id.appspot.com,your-custom-domain.com'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  - url: /static
    static_dir: staticfiles/

  # This handler routes all requests not caught above to your main app.
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
