# Generated by Django 4.2.27 on 2026-01-03 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('professional_summary', models.TextField(blank=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('alternative_mobile', models.CharField(blank=True, max_length=20)),
                ('alternative_email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('preferred_locations', models.JSONField(default=list)),
                ('languages_known', models.JSONField(default=list)),
                ('driving_license', models.BooleanField(default=False)),
                ('driving_license_issued_from', models.CharField(blank=True, max_length=100)),
                ('visa_status', models.CharField(blank=True, max_length=100)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('total_experience_months', models.PositiveIntegerField(default=0)),
                ('gcc_experience_months', models.PositiveIntegerField(default=0)),
                ('desired_availability_to_join', models.CharField(blank=True, max_length=100)),
                ('current_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('desired_monthly_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='AED', max_length=10)),
                ('desired_industry', models.CharField(blank=True, max_length=100)),
                ('desired_sub_industry', models.CharField(blank=True, max_length=100)),
                ('desired_functional_area', models.CharField(blank=True, max_length=100)),
                ('desired_designation_role', models.CharField(blank=True, max_length=100)),
                ('desired_job_location', models.CharField(blank=True, max_length=100)),
                ('job_search_status', models.CharField(blank=True, max_length=100)),
                ('professional_skills', models.JSONField(default=list)),
                ('functional_skills', models.JSONField(default=list)),
                ('it_skills', models.JSONField(default=list)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('cv_text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Profile',
                'verbose_name_plural': 'Candidate Profiles',
                'db_table': 'candidate_profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='candidates.candidateprofile')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'db_table': 'candidate_work_experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MajorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('role', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_projects', to='candidates.candidateprofile')),
            ],
            options={
                'verbose_name': 'Major Project',
                'verbose_name_plural': 'Major Projects',
                'db_table': 'candidate_major_projects',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ITSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('last_used', models.PositiveIntegerField(help_text='Year last used')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_skill_records', to='candidates.candidateprofile')),
            ],
            options={
                'verbose_name': 'IT Skill',
                'verbose_name_plural': 'IT Skills',
                'db_table': 'candidate_it_skills',
                'ordering': ['-last_used', 'skill_name'],
            },
        ),
        migrations.CreateModel(
            name='HonorAndAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('date_issued', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honors_and_awards', to='candidates.candidateprofile')),
            ],
            options={
                'verbose_name': 'Honor and Award',
                'verbose_name_plural': 'Honors and Awards',
                'db_table': 'candidate_honors_and_awards',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='candidates.candidateprofile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education History',
                'db_table': 'candidate_education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_score', models.FloatField(blank=True, null=True)),
                ('assessment_data', models.JSONField(blank=True, null=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-applied_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
