# Generated by Django 4.2.27 on 2026-01-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        # Rename ITSkill to ITSkillCertification
        migrations.RenameModel(
            old_name='ITSkill',
            new_name='ITSkillCertification',
        ),
        # Update the related_name
        migrations.AlterField(
            model_name='itskillcertification',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_skill_certifications', to='candidates.candidateprofile'),
        ),
        # Add new fields to ITSkillCertification
        migrations.AddField(
            model_name='itskillcertification',
            name='certification_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='itskillcertification',
            name='issuing_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='itskillcertification',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itskillcertification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        # Modify existing field
        migrations.AlterField(
            model_name='itskillcertification',
            name='last_used',
            field=models.PositiveIntegerField(blank=True, help_text='Year last used', null=True),
        ),
        # Update CandidateProfile
        migrations.AddField(
            model_name='candidateprofile',
            name='languages_spoken',
            field=models.TextField(blank=True, null=True),
        ),
        # Update Education fields
        migrations.AddField(
            model_name='education',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        # Update WorkExperience fields
        migrations.AddField(
            model_name='workexperience',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='functional_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        # Alter existing fields
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
