# Generated by Django 4.2.27 on 2026-01-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_itskillcertification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itskillcertification',
            options={'ordering': ['-issue_date', 'skill_name'], 'verbose_name': 'IT Skill & Certification', 'verbose_name_plural': 'IT Skills & Certifications'},
        ),
        migrations.AlterField(
            model_name='honorandaward',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='majorproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
