# Generated by Django 4.2.27 on 2026-01-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_make_date_fields_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate Profile', 'verbose_name_plural': 'Candidate Profiles'},
        ),
    ]
