# Generated by Django 4.2.27 on 2026-01-03 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('candidate_profile', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('keywords', models.JSONField(default=list)),
                ('company_name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(max_length=200)),
                ('is_gcc_location', models.BooleanField(default=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('job_country', models.CharField(blank=True, max_length=100)),
                ('min_experience_years', models.PositiveIntegerField(default=0)),
                ('max_experience_years', models.PositiveIntegerField(default=20)),
                ('min_gcc_experience_years', models.PositiveIntegerField(default=0)),
                ('required_education', models.CharField(blank=True, max_length=100)),
                ('preferred_education', models.CharField(blank=True, max_length=100)),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='AED', max_length=10)),
                ('hide_salary', models.BooleanField(default=False)),
                ('benefits', models.TextField(blank=True)),
                ('job_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive')], default='mid', max_length=20)),
                ('is_remote', models.BooleanField(default=False)),
                ('industry', models.CharField(default='Logistics', max_length=100)),
                ('sub_industry', models.CharField(blank=True, max_length=100)),
                ('functional_area', models.CharField(blank=True, max_length=100)),
                ('required_date_of_joining', models.CharField(blank=True, max_length=100)),
                ('process', models.CharField(blank=True, max_length=200)),
                ('mode_of_application', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
