# Generated by Django 4.2.27 on 2026-01-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visa_requirement',
            field=models.CharField(blank=True, help_text='Visa sponsorship or visa requirement details', max_length=200),
        ),
    ]
